export const restaurant = {
  name: 'Spice Garden Kitchen',
  description:
    'A simple QR-style menu built for browsing dishes quickly across starters, mains, rice, desserts, and drinks.',
  rating: '4.6 / 5',
  deliveryTime: '25-35 mins',
  cuisine: 'Indian, Tandoor, Cafe',
  hours: '11:00 AM - 11:00 PM',
  location: 'Hyderabad',
}

export const menuCategories = [
  {
    name: 'Starters',
    description: 'Small plates and fast-moving favourites.',
    items: [
      {
        id: 'starter-1',
        name: 'Paneer Tikka',
        description: 'Char-grilled cottage cheese cubes with mint marinade.',
        price: 289,
        prepTime: 15,
        spiceLevel: 'Medium spice',
        isVeg: true,
        isBestSeller: true,
      },
      {
        id: 'starter-2',
        name: 'Crispy Corn Pepper',
        description: 'Sweet corn tossed with peppers, onion, and house seasoning.',
        price: 219,
        prepTime: 10,
        spiceLevel: 'Mild spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'starter-3',
        name: 'Chicken 65',
        description: 'Classic fried chicken bites with curry leaf tempering.',
        price: 309,
        prepTime: 14,
        spiceLevel: 'Hot spice',
        isVeg: false,
        isBestSeller: true,
      },
    ],
  },
  {
    name: 'South Indian',
    description: 'Comfort plates with dosa, idli, and podi flavours.',
    items: [
      {
        id: 'south-1',
        name: 'Ghee Podi Idli',
        description: 'Mini idlis tossed with ghee and roasted podi masala.',
        price: 189,
        prepTime: 9,
        spiceLevel: 'Medium spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'south-2',
        name: 'Masala Dosa',
        description: 'Golden dosa with spiced potato masala and chutneys.',
        price: 159,
        prepTime: 12,
        spiceLevel: 'Mild spice',
        isVeg: true,
        isBestSeller: true,
      },
      {
        id: 'south-3',
        name: 'Karam Pesarattu',
        description: 'Green gram crepe served with ginger chutney.',
        price: 199,
        prepTime: 11,
        spiceLevel: 'Medium spice',
        isVeg: true,
        isBestSeller: false,
      },
    ],
  },
  {
    name: 'Main Course',
    description: 'Curries and rich gravies for lunch or dinner.',
    items: [
      {
        id: 'main-1',
        name: 'Paneer Butter Masala',
        description: 'Creamy tomato gravy with soft paneer and kasuri methi.',
        price: 329,
        prepTime: 16,
        spiceLevel: 'Mild spice',
        isVeg: true,
        isBestSeller: true,
      },
      {
        id: 'main-2',
        name: 'Kadai Vegetable',
        description: 'Seasonal vegetables in a smoky kadai masala.',
        price: 289,
        prepTime: 15,
        spiceLevel: 'Medium spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'main-3',
        name: 'Butter Chicken',
        description: 'Tandoor chicken folded into a rich makhani sauce.',
        price: 389,
        prepTime: 18,
        spiceLevel: 'Medium spice',
        isVeg: false,
        isBestSeller: true,
      },
    ],
  },
  {
    name: 'Breads',
    description: 'Tandoor breads to pair with your mains.',
    items: [
      {
        id: 'bread-1',
        name: 'Butter Naan',
        description: 'Soft leavened bread finished with butter.',
        price: 59,
        prepTime: 6,
        spiceLevel: 'No spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'bread-2',
        name: 'Garlic Naan',
        description: 'Tandoor naan topped with garlic and coriander.',
        price: 79,
        prepTime: 6,
        spiceLevel: 'No spice',
        isVeg: true,
        isBestSeller: true,
      },
      {
        id: 'bread-3',
        name: 'Tandoori Roti',
        description: 'Whole wheat flatbread from the clay oven.',
        price: 45,
        prepTime: 5,
        spiceLevel: 'No spice',
        isVeg: true,
        isBestSeller: false,
      },
    ],
  },
  {
    name: 'Rice & Biryani',
    description: 'Rice bowls and aromatic biryani plates.',
    items: [
      {
        id: 'rice-1',
        name: 'Veg Dum Biryani',
        description: 'Long grain rice layered with vegetables and saffron.',
        price: 269,
        prepTime: 18,
        spiceLevel: 'Medium spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'rice-2',
        name: 'Hyderabadi Chicken Biryani',
        description: 'Classic dum biryani with marinated chicken and herbs.',
        price: 359,
        prepTime: 20,
        spiceLevel: 'Hot spice',
        isVeg: false,
        isBestSeller: true,
      },
      {
        id: 'rice-3',
        name: 'Jeera Rice',
        description: 'Basmati rice tempered with cumin and ghee.',
        price: 149,
        prepTime: 8,
        spiceLevel: 'No spice',
        isVeg: true,
        isBestSeller: false,
      },
    ],
  },
  {
    name: 'Desserts',
    description: 'Classic sweets to close the meal.',
    items: [
      {
        id: 'dessert-1',
        name: 'Gulab Jamun',
        description: 'Warm khoya dumplings served in sugar syrup.',
        price: 119,
        prepTime: 5,
        spiceLevel: 'Sweet',
        isVeg: true,
        isBestSeller: true,
      },
      {
        id: 'dessert-2',
        name: 'Double Ka Meetha',
        description: 'Hyderabadi bread pudding with saffron and nuts.',
        price: 139,
        prepTime: 7,
        spiceLevel: 'Sweet',
        isVeg: true,
        isBestSeller: false,
      },
    ],
  },
  {
    name: 'Beverages',
    description: 'Coolers, shakes, and hot beverages.',
    items: [
      {
        id: 'drink-1',
        name: 'Sweet Lassi',
        description: 'Creamy yogurt drink chilled and lightly sweetened.',
        price: 99,
        prepTime: 4,
        spiceLevel: 'Sweet',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'drink-2',
        name: 'Masala Chaas',
        description: 'Spiced buttermilk with roasted cumin and mint.',
        price: 79,
        prepTime: 4,
        spiceLevel: 'Mild spice',
        isVeg: true,
        isBestSeller: false,
      },
      {
        id: 'drink-3',
        name: 'Cold Coffee',
        description: 'Blended coffee with milk and ice cream.',
        price: 149,
        prepTime: 6,
        spiceLevel: 'Sweet',
        isVeg: true,
        isBestSeller: true,
      },
    ],
  },
]
